class stack_with_list:
        def __init__(self, base_list):
                    self.top = -1
                            self.last = len(base_list)
                                    self.stacker = base_list
                                        
                                            def __repr__(self):
                                                        return f"{self.stacker} and top at {self.top} and last at {self.last}"
                                                            
                                                        def has_space(self):
                                                                    if self.top == self.last-1:
                                                                                    return False
                                                                                        else:
                                                                                                        return True
                                                                                                        
                                                                                                        def insert(self,val, stack_num):
                                                                                                                    if self.has_space():
                                                                                                                                    if stack_num == 1:
                                                                                                                                                        self.top+=1
                                                                                                                                                                        self.stacker[self.top] = val
                                                                                                                                                                                        
                                                                                                                                                                                                    else:
                                                                                                                                                                                                                        self.last-=1
                                                                                                                                                                                                                                        self.stacker[self.last] = val
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                ext = input("both the stacks are full, Do you want to extend? [y/n]")
                                                                                                                                                                                                                                                                                            if ext == 'y':
                                                                                                                                                                                                                                                                                                                ext_by = int(input("enter a num to extend by:  "))
                                                                                                                                                                                                                                                                                                                                self.extend(ext_by)
                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                print("I keep the stacks as they are")
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                        def extend(self, ext_by):
                                                                                                                                                                                                                                                                                                                                                                                                    print("\n")
                                                                                                                                                                                                                                                                                                                                                                                                            print("-----------extend----------")
                                                                                                                                                                                                                                                                                                                                                                                                                    cur_st_1 = self.top
                                                                                                                                                                                                                                                                                                                                                                                                                            cur_st_2 = self.last
                                                                                                                                                                                                                                                                                                                                                                                                                                    new_base_list = [None]*(len(self.stacker)+ext_by)
                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"top_at: {self.top} and last_at: {self.last}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                    if self.top != -1: new_base_list[0] = self.stacker[0]
                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("1st element inserted")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if self.top > 0:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("top more than 0")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for i in range(1,self.top+1):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    new_base_list[i] = self.stacker[i]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for i in range(self.last, len(self.stacker)):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            new_base_list[i+ext_by] = self.stacker[i]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    self.stacker = new_base_list
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.last += ext_by
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"new size: {len(self.stacker)} top at {self.top} and last_at {self.last}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("----------------------------")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            stacker = stack_with_list([None]*4)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            stacker.insert(3,2)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            stacker.insert(6,1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(stacker)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            stacker.insert(7,2)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(stacker)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            stacker.insert(8,1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(stacker)
